# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubelog < Formula
  desc "CLI tool to fetch and enhance Kubernetes pod logs"
  homepage "https://github.com/dantech2000/kubelog"
  version "0.1.2"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/dantech2000/kubelog/releases/download/v0.1.2/kubelog_Darwin_x86_64.tar.gz"
      sha256 "45eb3b491d4b05f35d32234dafc87124621613f81cb35ba3dc3b36d4faaf1015"

      def install
        bin.install "kubelog"
      end
    end
    on_arm do
      url "https://github.com/dantech2000/kubelog/releases/download/v0.1.2/kubelog_Darwin_arm64.tar.gz"
      sha256 "e93b9ba6eadf446c4e418786923acb96390f877042685200d243c77e6361ea50"

      def install
        bin.install "kubelog"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dantech2000/kubelog/releases/download/v0.1.2/kubelog_Linux_x86_64.tar.gz"
        sha256 "cf945d2209f4114e118f5d02da0453b45be6e7b62792b4526966ce505abe5f39"

        def install
          bin.install "kubelog"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dantech2000/kubelog/releases/download/v0.1.2/kubelog_Linux_arm64.tar.gz"
        sha256 "33d7b061ba508728f06124799ac7d6aab51626242f3678c7d932d3707be833d1"

        def install
          bin.install "kubelog"
        end
      end
    end
  end

  test do
    system "#{bin}/kubelog version"
  end
end
