# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubelog < Formula
  desc "CLI tool to fetch and enhance Kubernetes pod logs"
  homepage "https://github.com/dantech2000/kubelog"
  version "0.1.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/dantech2000/kubelog/releases/download/v0.1.3/kubelog_Darwin_x86_64.tar.gz"
      sha256 "e5d03159bbf0170fd92cfaa6f8dc6475d0d64b01591c480305a9e8cc0f3d2212"

      def install
        bin.install "kubelog"
      end
    end
    on_arm do
      url "https://github.com/dantech2000/kubelog/releases/download/v0.1.3/kubelog_Darwin_arm64.tar.gz"
      sha256 "540dded5fc894cdad0b26a7b7dc6ef7299fc9ba69814a83cdc127ece070f4557"

      def install
        bin.install "kubelog"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dantech2000/kubelog/releases/download/v0.1.3/kubelog_Linux_x86_64.tar.gz"
        sha256 "82505841ac00d3d958cc8638c331215f82128d066e8adf8fc93d8cb32a86ba14"

        def install
          bin.install "kubelog"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dantech2000/kubelog/releases/download/v0.1.3/kubelog_Linux_arm64.tar.gz"
        sha256 "e750ec67758dde821228e0e9c0a359f397a52887f333a89d66612bea8dd269f6"

        def install
          bin.install "kubelog"
        end
      end
    end
  end

  test do
    system "#{bin}/kubelog version"
  end
end
