# This file is generated by digg's release workflow. DO NOT EDIT.
cask "digg" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "5e44ee0008667f89519daae7abf4f60f8fe38a301d149ee202be2959114feab7"
      url "https://github.com/dantech2000/digg/releases/download/v#{version}/digg_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0b6119a5c76a016637d450f4a99b55ba446cb12af8f2f3a77ba07cc81b10faaa"
      url "https://github.com/dantech2000/digg/releases/download/v#{version}/digg_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "digg"
  desc "Modern DNS lookup CLI"
  homepage "https://github.com/dantech2000/digg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "digg"

  # The release binary is not Developer ID-signed. Match the other CLI casks
  # in this tap by clearing the download quarantine after Homebrew stages it.
  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/digg"]
    end
  end
end
