# This file is generated by digg's release workflow. DO NOT EDIT.
cask "digg" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "8cf5abbcc68b008f54c499c65778054d6c648cb67feb5ec9f66003c25c99e0bc"
      url "https://github.com/dantech2000/digg/releases/download/v#{version}/digg_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "de5a045daac7fa9a0e63c90b75c3b6ff747383a50f4417cb4a8ddaa5de221dfc"
      url "https://github.com/dantech2000/digg/releases/download/v#{version}/digg_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "digg"
  desc "Modern DNS lookup CLI"
  homepage "https://github.com/dantech2000/digg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "digg"
  manpage "digg.1"
  binary "completions/digg.bash", target: "#{HOMEBREW_PREFIX}/etc/bash_completion.d/digg"
  binary "completions/_digg", target: "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_digg"
  binary "completions/digg.fish", target: "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/digg.fish"

  # The release binary is not Developer ID-signed. Match the other CLI casks
  # in this tap by clearing the download quarantine after Homebrew stages it.
  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/digg"]
    end
  end
end
