# This file is generated by digg's release workflow. DO NOT EDIT.
cask "digg" do
  version "0.5.3"

  on_macos do
    on_intel do
      sha256 "1d0a89351602191d9dd0bea6bd02ad60d6b6e3b8e5399e4cee0bf4809052156d"
      url "https://github.com/dantech2000/digg/releases/download/v#{version}/digg_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1e1ddc76ffc4d3ec31f253ee2222b26067bd3cffaefe1e19194873d20f2aa2fe"
      url "https://github.com/dantech2000/digg/releases/download/v#{version}/digg_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "digg"
  desc "Modern DNS lookup CLI"
  homepage "https://github.com/dantech2000/digg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "digg"
  manpage "digg.1"
  binary "completions/digg.bash", target: "#{HOMEBREW_PREFIX}/etc/bash_completion.d/digg"
  binary "completions/_digg", target: "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_digg"
  binary "completions/digg.fish", target: "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/digg.fish"

  # The release binary is not Developer ID-signed. Match the other CLI casks
  # in this tap by clearing the download quarantine after Homebrew stages it.
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/digg"]
    end
  end
end
