# This file was generated by GoReleaser. DO NOT EDIT.
cask "logx" do
  version "0.2.3"

  on_macos do
    on_intel do
      sha256 "522bdc19f682af29c2acb73df4adba9751368987d1f445f2cc92740077d6591e"
      url "https://github.com/dantech2000/logx/releases/download/v#{version}/logx_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "9cd9c79de08150b015ac35dab6b83c6327f3371bc159a6446f6c0d95512bfe3f"
      url "https://github.com/dantech2000/logx/releases/download/v#{version}/logx_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "240d5567a9921d8a4158b9412f65c0246a56180d811d1dc554c1d1cb4398ff09"
      url "https://github.com/dantech2000/logx/releases/download/v#{version}/logx_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e9f97d63cbe8070b51ddfcf1c378fc93334ea744ef71f709b1b5f3bbad613b51"
      url "https://github.com/dantech2000/logx/releases/download/v#{version}/logx_Linux_arm64.tar.gz"
    end
  end

  name "logx"
  desc "Enhanced Kubernetes pod log viewer"
  homepage "https://github.com/dantech2000/logx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "logx"
  binary "kubectl-logx"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/logx"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubectl-logx"]
    end
  end

  # No zap stanza required

end
