# This file was generated by GoReleaser. DO NOT EDIT.
cask "logx" do
  version "0.2.4"

  on_macos do
    on_intel do
      sha256 "4e6e29a75a466979419399aaaaef5a55333ab654f6f1d1c0f0049e6b680f19f5"
      url "https://github.com/dantech2000/logx/releases/download/v#{version}/logx_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8a99df0212e97006a2da5c55280b8c63ff89d1122a06d294e2b99a93c410e24b"
      url "https://github.com/dantech2000/logx/releases/download/v#{version}/logx_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e6388d4dd04d176163c735fd986307048dda5bd95787c94b2542ee9ed6ba5dfd"
      url "https://github.com/dantech2000/logx/releases/download/v#{version}/logx_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "510e2e7efda8fd35f78e23eea430e3c2d2e1e6786e8aa08bfa0dc4a512de2e13"
      url "https://github.com/dantech2000/logx/releases/download/v#{version}/logx_Linux_arm64.tar.gz"
    end
  end

  name "logx"
  desc "Enhanced Kubernetes pod log viewer"
  homepage "https://github.com/dantech2000/logx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "logx"
  binary "kubectl-logx"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/logx"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kubectl-logx"]
    end
  end

  # No zap stanza required

end
