# This file was generated by GoReleaser. DO NOT EDIT.
cask "logx" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "cc7168c3474f11664208b9c038465ba6c65247c04e5b74190749ad0841ff8f3c"
      url "https://github.com/dantech2000/logx/releases/download/v#{version}/logx_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f65528ed4cc732ea3ebea7f6d48b1ad22cc46673fd171728782bc43d87e93d00"
      url "https://github.com/dantech2000/logx/releases/download/v#{version}/logx_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c299a5638dc2be0d604c04219e562d26f9d893f7bd5d8472305fcee0e824fc01"
      url "https://github.com/dantech2000/logx/releases/download/v#{version}/logx_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "32123e3be2f7d55349146d736ad23c16f7fb7fde011736ca0a021d94b81e3581"
      url "https://github.com/dantech2000/logx/releases/download/v#{version}/logx_Linux_arm64.tar.gz"
    end
  end

  name "logx"
  desc "Enhanced Kubernetes pod log viewer"
  homepage "https://github.com/dantech2000/logx"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "logx"
  binary "kubectl-logx"

  # No zap stanza required

end
