# This file was generated by GoReleaser. DO NOT EDIT.
cask "refresh" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/refresh"]
    end
  end

  version "0.10.4"

  on_macos do
    on_arm do
      sha256 "12b51e2ac3bec7710af397675a17a9b78aa9e62f4f3b586785f4405491ef63a4"
      url "https://github.com/dantech2000/refresh/releases/download/v#{version}/refresh_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "db4450f2d39366572e64976fe5243a473f9d44c44bc83dd7a57ebd93002787dd"
      url "https://github.com/dantech2000/refresh/releases/download/v#{version}/refresh_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "717bddfc2c61cb5b8eed547ca85f371ae0ab49b35eb2ee4e41d1e9b0c9cfcd92"
      url "https://github.com/dantech2000/refresh/releases/download/v#{version}/refresh_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c0ff1e7c71f19d47eba104afab819f7c59b8c86006211f0d7d7a9945b85c4f0b"
      url "https://github.com/dantech2000/refresh/releases/download/v#{version}/refresh_#{version}_linux_amd64.tar.gz"
    end
  end

  name "refresh"
  desc "Manage and monitor AWS EKS node groups using your local kubeconfig and AWS credentials"
  homepage "https://github.com/dantech2000/refresh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "refresh"

  # No zap stanza required
end
