# This file was generated by GoReleaser. DO NOT EDIT.
cask "refresh" do
  version "0.10.1"

  on_macos do
    on_arm do
      sha256 "8d6862b9ee43363eefad7631b5e7da71438715c30673d8e970add10226786ac1"
      url "https://github.com/dantech2000/refresh/releases/download/v#{version}/refresh_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3654690071f32f6d4e7a1eacce805643e535e8af4ed86005bf9e48d54f174495"
      url "https://github.com/dantech2000/refresh/releases/download/v#{version}/refresh_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "98e7262b17b06383fff48077579f0b22728cf52523b8afd1eaa31dad1dba996c"
      url "https://github.com/dantech2000/refresh/releases/download/v#{version}/refresh_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b9a6163bf5c9b3c0c5dda8a55dc811725d93a311267a294b8762c791c1892f21"
      url "https://github.com/dantech2000/refresh/releases/download/v#{version}/refresh_#{version}_linux_amd64.tar.gz"
    end
  end

  name "refresh"
  desc "Manage and monitor AWS EKS node groups using your local kubeconfig and AWS credentials"
  homepage "https://github.com/dantech2000/refresh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "refresh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/refresh"]
    end
  end

  # No zap stanza required
end
