# This file was generated by GoReleaser. DO NOT EDIT.
cask "refresh" do
  version "0.8.0"

  on_macos do
    on_intel do
      sha256 "a649fcec6e3a8b491f75b99b4ec8ceb58c91ba26708435adbfb4d1d64f35bbda"
      url "https://github.com/dantech2000/refresh/releases/download/v#{version}/refresh_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ba7ee4709e21d063f2878b492aa12073cc1eee200d399e2eda4ac72e6b1243e4"
      url "https://github.com/dantech2000/refresh/releases/download/v#{version}/refresh_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5a7c1f9e7cbac283f7deb59d296b762c37387c8726d6a36c9c576a6cae652e54"
      url "https://github.com/dantech2000/refresh/releases/download/v#{version}/refresh_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "568b4687e694565a9848a503347dcdea0a3427dcd3c54233bc4bca6e7d8cdf12"
      url "https://github.com/dantech2000/refresh/releases/download/v#{version}/refresh_#{version}_linux_arm64.tar.gz"
    end
  end

  name "refresh"
  desc "Manage and monitor AWS EKS node groups using your local kubeconfig and AWS credentials"
  homepage "https://github.com/dantech2000/refresh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "refresh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/refresh"]
    end
  end

  # No zap stanza required

end
