# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Refresh < Formula
  desc "Manage and monitor AWS EKS node groups using your local kubeconfig and AWS credentials"
  homepage "https://github.com/dantech2000/refresh"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dantech2000/refresh/releases/download/v0.1.6/refresh_0.1.6_darwin_amd64.tar.gz"
      sha256 "94511f4b4b86887b30377d1ad1404aa9bd08d42920580b797cdf4d90149d1428"

      def install
        bin.install "refresh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dantech2000/refresh/releases/download/v0.1.6/refresh_0.1.6_darwin_arm64.tar.gz"
      sha256 "51878bc3dac7f055400795c0f76cc1f918d24aeafc47964ef344d6b19ee4e7e6"

      def install
        bin.install "refresh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/dantech2000/refresh/releases/download/v0.1.6/refresh_0.1.6_linux_amd64.tar.gz"
      sha256 "ccd3ae5bd866a2547ae8a3faf7cdace4d9a0576f2480bbb5457c60bb12b4de85"
      def install
        bin.install "refresh"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/dantech2000/refresh/releases/download/v0.1.6/refresh_0.1.6_linux_arm64.tar.gz"
      sha256 "12edf9d6d940aa87838b3fe639e6c8af7e1fb1c19ed2cbac83032ce53ed8e5f3"
      def install
        bin.install "refresh"
      end
    end
  end

  test do
    system "#{bin}/refresh version"
  end
end
