# This file was generated by GoReleaser. DO NOT EDIT.
class Refresh < Formula
  desc "Manage and monitor AWS EKS node groups"
  homepage "https://github.com/dantech2000/refresh"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/dantech2000/refresh/releases/download/v0.1.2/refresh_0.1.2_darwin_arm64.tar.gz"
      sha256 "placeholder_sha256_arm64"

      def install
        bin.install "refresh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dantech2000/refresh/releases/download/v0.1.2/refresh_0.1.2_darwin_amd64.tar.gz"
      sha256 "placeholder_sha256_amd64"

      def install
        bin.install "refresh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dantech2000/refresh/releases/download/v0.1.2/refresh_0.1.2_linux_arm64.tar.gz"
      sha256 "placeholder_sha256_linux_arm64"

      def install
        bin.install "refresh"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/dantech2000/refresh/releases/download/v0.1.2/refresh_0.1.2_linux_amd64.tar.gz"
      sha256 "placeholder_sha256_linux_amd64"

      def install
        bin.install "refresh"
      end
    end
  end

  test do
    system "#{bin}/refresh", "version"
  end
end
